image-fetcher {
    input-image-directory-path: "/path/to/images/"
    output-image-directory-path: "/path/to/images/"
    holding-event-ids: [1]
}

event-result-fetcher {
    holding-event-ids: [1]
    start-date: "2018-01-01"
    end-date: "2026-12-31"
}
