
ALTER TABLE expansions ADD COLUMN pg INT NULL;

UPDATE expansions SET pg = 870  WHERE id = 'sv1S';
UPDATE expansions SET pg = 871  WHERE id = 'sv1V';
UPDATE expansions SET pg = 877  WHERE id = 'sv1a';
UPDATE expansions SET pg = 878  WHERE id = 'svC';
UPDATE expansions SET pg = 879  WHERE id = 'sv2P';
UPDATE expansions SET pg = 880  WHERE id = 'sv2D';
UPDATE expansions SET pg = 882  WHERE id = 'sv2a';
UPDATE expansions SET pg = 884  WHERE id = 'svD';
UPDATE expansions SET pg = 894  WHERE id = 'sv3';
UPDATE expansions SET pg = 897  WHERE id = 'sv3a';
UPDATE expansions SET pg = 898  WHERE id = 'svEM';
UPDATE expansions SET pg = 899  WHERE id = 'svEL';
UPDATE expansions SET pg = 901  WHERE id = 'sv4K';
UPDATE expansions SET pg = 902  WHERE id = 'sv4M';
UPDATE expansions SET pg = 905  WHERE id = 'sv4a';
UPDATE expansions SET pg = 906  WHERE id = 'sv5K';
UPDATE expansions SET pg = 907  WHERE id = 'sv5M';
UPDATE expansions SET pg = 908  WHERE id = 'svHK';
UPDATE expansions SET pg = 909  WHERE id = 'svHM';
UPDATE expansions SET pg = 911  WHERE id = 'svI';
UPDATE expansions SET pg = 913  WHERE id = 'sv5a';
UPDATE expansions SET pg = 914  WHERE id = 'sv6';
UPDATE expansions SET pg = 915  WHERE id = 'svJL';
UPDATE expansions SET pg = 916  WHERE id = 'svJP';
UPDATE expansions SET pg = 917  WHERE id = 'sv6a';
UPDATE expansions SET pg = 918  WHERE id = 'sv7';
UPDATE expansions SET pg = 920  WHERE id = 'svLS';
UPDATE expansions SET pg = 921  WHERE id = 'svLN';
UPDATE expansions SET pg = 922  WHERE id = 'sv7a';
UPDATE expansions SET pg = 923  WHERE id = 'sv8';
UPDATE expansions SET pg = 925  WHERE id = 'svM';
UPDATE expansions SET pg = 934  WHERE id = 'sv8a';
UPDATE expansions SET pg = 935  WHERE id = 'sv9';
UPDATE expansions SET pg = 938  WHERE id = 'svOM';
UPDATE expansions SET pg = 939  WHERE id = 'svOD';
UPDATE expansions SET pg = 940  WHERE id = 'sv9a';
UPDATE expansions SET pg = 941  WHERE id = 'sv10';
UPDATE expansions SET pg = 942  WHERE id = 'sv11B';
UPDATE expansions SET pg = 943  WHERE id = 'sv11W';
UPDATE expansions SET pg = 944  WHERE id = 'm1L';
UPDATE expansions SET pg = 945  WHERE id = 'm1S';
UPDATE expansions SET pg = 947  WHERE id = 'mBG';
UPDATE expansions SET pg = 948  WHERE id = 'mBD';
UPDATE expansions SET pg = 949  WHERE id = 'm2';
UPDATE expansions SET pg = 950  WHERE id = 'm2a';
UPDATE expansions SET pg = 951  WHERE id = 'mC';
UPDATE expansions SET pg = 952  WHERE id = 'm3';

ALTER TABLE expansions MODIFY COLUMN pg INT NOT NULL;
